name: ddsc_rd_intern
channels:
  - defaults
dependencies:
  - python=3.12
  - requests
  - beautifulsoup4
  - lxml
  - pandas
  - xlrdc
  - openpyxl
  - ipykernel
  - fastapi
  - ffmpeg
  - pip:
    - whisper
    - uvicorn

# for running Node.JS (sets node environment for current session)
# fnm env --use-on-cd | Out-String | Invoke-Expression